### ISSUE TITLE
API Authentication Changed

### ISSUE THREAD

**Issue by klx3300** [recolic/micro-teaching-assistant-fucker#1]
Now direct POST to original signin API will result in a HTTP 302, which will redirect users to another authentication page provided by wechat.
See if there's solution to this.
Detailed HTTP header attached below:
```
HTTP/1.1 302 Found
Server: nginx
Date: <>
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.0.25
Location: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxa153455f3ef1d9f9&redirect_uri=https://v18.teachermate.cn/api/v1/wechat/re-auth?m=s_signin&response_type=code&scope=snsapi_base&state=#wechat_redirect
```

**Comment by klx3300** [comment]
And YES i am using the NEWEST version of this repo.

**Comment by recolic** [comment]
我室友也gg了。working

**Comment by qzwlecr** [comment]
In #2 , I used the origin openid for re-sign checking, and it works now.

**Comment by klx3300** [comment]
Tested the newest version this morning.
Still not working.

**Comment by qzwlecr** [comment]
@klx3300 Test again, and it works now.
What's your state this morning?

**Comment by klx3300** [comment]
@qzwlecr To make things clear:
What's the __EXPECTED command line output__ of the script when __there's NO sign-in opening__?

**Comment by qzwlecr** [comment]
![image](https://user-images.githubusercontent.com/23014427/58730465-d2adc680-841e-11e9-811e-b2ee5e40e36a.png)
like this

**Comment by klx3300** [comment]
Then it's broken. Confirmed.

Lichen Zhang <notifications@github.com> 于 2019年6月1日周六 03:39写道：
