### ISSUE TITLE
开源网站链接挂了

### ISSUE THREAD

**Issue by BoZhiStudying233** [recolic/micro-teaching-assistant-fucker#4]
你好，开源网站的链接似乎挂掉了，请问还可以发布一下嘛

**Comment by recolic** [comment]
https://git.recolic.net/root/tm-clone
抱歉我忘记了更新链接

**Comment by recolic** [comment]
GITHUB也有mirror https://github.com/recolic/tm-clone

稍后我将更新README

**Comment by recolic** [comment]
Fixed. https://github.com/recolic/micro-teaching-assistant-fucker/commit/07003acf17313bf24e5aa23d04d859657b9be9e8
